### ISSUE TITLE
/new doesn't paginate

### ISSUE THREAD

**Issue by florida** [kristoferbaxter/react-hn#7]
Repro Steps:

1. Navigate to https://react-hn.kristoferbaxter.com/new
2. Click `next >`
3. List doesn't paginate, but it appends the content to the bottom of the list.

**Comment by kristoferbaxter** [comment]
Thanks for the bug report!

I just submitted a fix for this with https://github.com/kristoferbaxter/react-hn/commit/de8b4033998782b679740e09c6803e62b23d0f57.
